theme: jekyll-theme-time-machine

# Name of your site (displayed in the header)
#name: Your Name

# Short bio or description (displayed in the header)
description: What if

# URL of your avatar or profile pic (you could use your GitHub profile pic)
#avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: zanella-github-io

url: https://zanella.github.io/

